### ISSUE TITLE
returnvalue getState()

### ISSUE THREAD

**Issue by SchmadenSchmuki** [google/oboe#37]
Hello
I'm getting unexpected results with the oboe::AudioStream::getState()-function.
After opening a stream getstate() returns the expected result 2 (for open).
After calling requestStart(), everything seems to work, I get a soundoutput, but when I call getState() I always only get a the returnvalue 3 (for starting).
The same with requestStop(), sound stops, but returnvalue is 9 (for stopping).

I am an unexperienced programmer, so maybe I'm made a mistake (even a basic one).

If it matters, I'm running AndroidStudio 3.0.1 on Windows 10 with Android Emulator.
minSdkVersion 16
targetSdkVersion 26

greetings
SchmadenSchmuki

**Comment by dturner** [comment]
Hello SchmadenSchmuki, 

Many thanks for filing this issue. What API version are you using on the emulator? There was an internal bug (id: 62781173) which matches the behaviour you're experiencing but this was fixed in API 27 (Oreo MR1).

**Comment by SchmadenSchmuki** [comment]
Thanks for the help.
Changed the API in the emulator to 27 and that was partly successful.
I now get the expected result after requestStart, so 4 for started,
after requestStop it's still the same, result of 9 for stopping (sound stopped).

So, if I'm testing on a real phone I won't have this problem?

Thanks a lot
SchmadenSchmuki

**Comment by dturner** [comment]
I have a feeling you may have found a bug. Currently investigating.

**Comment by SchmadenSchmuki** [comment]
Played a little around with AAudio as well and noticed the same behaviour, AAudioStream_requestStop(), sound stopped but AAudioStream_getState() returnvalue remained 9.
So maybe it has something to do with AAudio (executed on android emulator API 27, minSdkVersion 26, targetSdkVersion 26).

**Comment by dturner** [comment]
Actions: Phil has a spreadsheet which contains all the state transitions, this needs publishing.

**Comment by philburk** [comment]
requestStart() can take a while to actually start. But should change to STARTED state within 200-300 msec. requestStop() had a problem where the state got stuck at STOPPING even though the stream was actually stopped. This is a known bug for LOW_LATENCY mode on some devices in O and O-MR1. It is fixed but the fix is not yet released.

internal bug b/69810494
