### ISSUE TITLE
Multichannel not working properly on Samsung Galaxy s10

### ISSUE THREAD

**Issue by apleton** [google/oboe#943]
Android version(s): 9
Android device(s): Samsung Galaxy s10
Oboe version: 1.4.2
App name used for testing: 
Hello Oboe
 
**Short description**
The sample app “Hello Oboe” does not use correctly the 4 channels when it is connected to an audio interface with 2 stereo outputs. 

**Steps to reproduce**
- launch the sample app “Hello Oboe” on a galaxy s10, connected to a multichannel audio interface (in my case Pioneer WeGo4 or Reloop BeatPad2) via USB. 
- Select “Channel count” : 4
- Play the sound by touching the screen

**Expected behavior**
Each output of the audio interface should play a sine signal with a different pitch. 

**Actual behavior**
The main output play sine signals with different pitches mixed together. There is no sound coming from the second stereo output.   

**Any additional context**
- The same issue is observed in other Oboe apps. 
- It may also happen with Galaxy Note 10. Not 100% sure though.

**Comment by philburk** [comment]
>  There is no sound coming from the second stereo output.

@apleton - Do you mean the second speaker or channels {2,3}?

The latter is expected. Higher channels are not folded down.

Have you tried this on any non-Samsung devices?

**Comment by apleton** [comment]
- The audio interfaces are dual stereo dj controllers. The second output is used for pre-cuing. 
- It works as expected on other android devices (tested with Moto, Pixel, and Huawei)

**Comment by dturner** [comment]
I tested this using the following setup (which is the closest hardware I have to this): 

Phone: Samsung Galaxy S9  running Android 10 (build QPA1.190711.020.G965FXXSBETH2)
DJ controller: Pioneer DDJ-WEGO3

The 4 sine waves played as expected so I'm guessing this is an S10 specific issue. 

@apleton Are you able to update your Galaxy S10 to Android 10 and retest?

**Comment by apleton** [comment]
I retested with a Samsung Galaxy S10 running Android 10 -> same result :
- 2 sine waves mixed together on channel 1 and 2
- silence on channel 3 and 4

**Comment by dturner** [comment]
Please could you [take a bug report](https://developer.android.com/studio/debug/bug-report) and attach. We'll then file an issue with Samsung.

**Comment by apleton** [comment]
@dturner I've sent you the bug report.

**Comment by dturner** [comment]
Many thanks for sending this over. Bug filed with Samsung b/171542691

**Comment by philburk** [comment]
@dturner - What happens if you run the same test on a Pixel device running P?
How about on R or S?

**Comment by philburk** [comment]
I tested with  Pixel 3a XL running R (11) on a Presonus Studio 26C, which has 4 outputs. I was able to get all 4 channels with separate signals using OboeTester. It worked for AAudio Legacy and OpenSL ES.

On a Pixel 2 XL (Taimen)  running P (9) I got channels 3&4 mapped onto channels 1&2. Same on AAudio and OpenSL ES. That matches what apleton described. I got the same result on an S10e running PPR1 (9).

**Comment by philburk** [comment]
So this seems to have been fixed on Q or R. It is not specific to Samsung. It also happens on Pixel.
Closing as Fixed.

Please reopen if you see this on a Samsung device running R+.

**Comment by apleton** [comment]
We still have the issue on galaxy S20 running Android 11 : no sound on channels 3/4. Pixel 3A android 11 works fine.

**Comment by triplef** [comment]
We continue to have many users run into this issue with various Samsung devices running Android 10 and 11, and it is significantly hurting our ability to market our app for use with external audio/MIDI devices given that Samsung devices have the biggest market share.

Is there any update on the bug on Samsung’s side (b/171542691), or anything we can do to ensure this gets fixed at least for the next major release?

**Comment by Thundermaxx** [comment]
Here a Samsung S20U Android 11 UI 3.1 Cross DJ with U-Mix Control Pro soundcard, no sound from output 3/4 and all channels are summed up on output 1/2. Midi control works and the soundcard is connected because the app switches to Dual Audio outputs when a compatible controller is connected. Works perfectly with other devices. Hope they fixed the problem in Android 12.

**Comment by Thundermaxx** [comment]
@Appleton - Android 12 will soon arrive on the S10 and is already available in beta. Would be great if someone could check if this issue has eventually been adressed.

**Comment by triplef** [comment]
I was just looking at the [Android 12 Compatibility Definition](https://source.android.com/compatibility/12/android-12-cdd?hl=en), which defines the requirements for the [performance class 12](https://developer.android.com/topic/performance/performance-class). In there it says the following regarding multi-channel audio support:

> [C-SR] Are STRONGLY RECOMMENDED to support simultaneous I/O up to 8 channels each direction, 96 kHz sample rate, and 24-bit or 32-bit depth, when used with USB audio peripherals that also support these requirements.

@dturner is there any way to have this language updated for the next CDD so that multi-channel audio MUST be supported? (48 or 44.1 kHz sample rate would be sufficient at least for our use case.)

At the last audio summit we talked about increasing the vendor requirements around testing multi-channel audio, and it seems like this might be a way to do this and ensure future devices support this. The fact that we cannot guarantee support for multi-channel audio with all Android devices is our top issue on Android, as it means that users might spend hundreds of dollars on hardware (e.g. DJ controllers) only to find out at home that it doesn’t work as expected, and we cannot even provide a list of supported or not supported devices as there are just too many.

**Comment by 5A52** [comment]
Hello. Unfortunattely this is definitely  Samsung bug (regression). I`m experimenting with Galaxy S7 and S10e (both rooted), and USB multichannel sound cards (Asus xonar u7 and "cm106 like") Both are working multichannel with S7 (android 8/9/10) and none with S10 (android 10/11, didn't try A12 as I know multichannel will not work, and it will be impossible to go back to 10/11 because of updated version of boot loader for A12). I believe samsung will not fix this, as even S20 (next generation) have same issue. For the moment I found this is not kernel and audio_policy related, but something with samsung implementation of android mediaserver. I have some linux knowledge but know nothing about android sound system (digging blind). If someone also is interested in this, I will be happy to participate in fixing this.

**Comment by philburk** [comment]
@triplef - Thank you both for raising these issues. I agree we should have stronger requirements fpr multi-channel audio. We have been adding MUST requirements for latency and need to do something similar for channel counts.

We need to review requirements for ProAudio, Media Performance Class and basic devices regarding multi-channel and data formats. I am guessing that high-res data formats are more important for audiophiles who listen to stereo audio. And N>=4 channels is more important for DJs. But both would be nice.

@5A52 (ZR) - I will contact Samsung and try to find out what is happening with the N>=4 channel support.

**Comment by philburk** [comment]
I see that [b/171542691](http://b/171542691) |  Galaxy S10 does not support USB audio devices with >2 audio channels
was opened then closed. I will reopen it.

**Comment by philburk** [comment]
This is getting confusing so I made a chart.

| Device | Version | Status | Reporter |
| ----- | ----- | ----- | ----- |
| S10 | 9, 10 | fail | apleton |
| S9 | 10 | OK | donturner |
| Pixel 3a | 11 | OK | philburk |
| Pixel 2 | 9 | fail | philburk |
| S10 | 9 | fail | philburk |
| S20 | 11 | fail | apleton |
| Pixel 3a | 11 | OK | apleton |
| S20u | 11 | fail | Thundermaxx |
|  S7 | 8,9,10 | OK | 5A52 |
| S10 | 10, 11 | fail | 5A52 |
| Samsung A51 | 11 | OK | philburk |
| Samsung Note10 Lite | 11 | OK | philburk |
| Pixel 6 | 13 | OK | philburk |

I think the most significant results are the results on Android 11. Pixel, Note 10 and  A51 are working. S10 and S20 are not.
I did my recent  tests with a Vantec 8 channel USB audio adapter.

**Comment by philburk** [comment]
@triplef I created internal bug b/235411530 | CDD needs review for multi-channel USB audio requirements
It references this discussion.
There have been some improvements in the T requirements. But I cannot go into detail.

**Comment by triplef** [comment]
Thank you @philburk, very much appreciated. Not being able to rely on multi-channel audio support is significantly holding back pro audio apps on Android, and we'd very much support stronger vendor requirements around this. Please let me know if there's anything else we can do to help make this happen.

**Comment by macpacrac** [comment]
I will also contribute with information.
I use a Pioneer DJ DDJ-400 as a DJ device.
On Samsung A52s 5G - not working (missing channels for precue - 3,4).
Motorola G8 Plus - OK
Lenovo TAB4 10 - OK

**Comment by 5A52** [comment]
So sorry, can someone please check with **galaxy note 9** exynos? Dont want to buy useless peace of hardware

**Comment by triplef** [comment]
@philburk thank you for making this a P1. Would you be able to give us an update as to where this stands both internally at Google and anything you can share from the communication with Samsung (e.g. b/171542691)?

Reading through the above I’m a bit confused that [you said](https://github.com/google/oboe/issues/943#issuecomment-1150528332) that Samsung A51 and Note10 Lite running Android 11 worked. We’ve unfortunately seen this issue persist with both Android 11 and 12 (in addition to 9 and 10) with various Samsung devices. Also according to some users various Sony devices are affected as well.

**Comment by triplef** [comment]
> @triplef I created internal bug b/235411530 | CDD needs review for multi-channel USB audio requirements
> It references this discussion.
> There have been some improvements in the T requirements. But I cannot go into detail.

Looks like the [Android 13 CDD](https://source.android.com/docs/compatibility/13/android-13-cdd?hl=en#2271_media) adds a requirement for >=4 channel USB audio for the T performance class:

> **2.2.7.1. Media**
> If Handheld device implementations return android.os.Build.VERSION_CODES.T for android.os.Build.VERSION_CODES.MEDIA_PERFORMANCE_CLASS, then they:
> ...
> * [5.6/H-1-4] MUST support >=4 channel USB audio devices (This is used by DJ controllers for previewing songs.)

While I appreciate the progress, as far as I understand this unfortunately means there will still be many devices _not_ supporting this, at least for the next couple of years until the T performance class becomes universal (?).

**Comment by philburk** [comment]
Thanks for reporting this. It will take a while for the fixes to propagate.
We will work on improving the tests so that these sorts of bugs do not happen in the future.
That work is being tracked internally.
Closing this now as there is nothing more we can do in Oboe.
